language: java
matrix:
  include:
    - os: osx
      language: bash
      # for jdk 11.0.1+13
      osx_image: xcode10.1
    - os: linux
      dist: trusty
      language: java
      jdk: openjdk8
      script: ./mvnw -B -e verify site site:stage
      after_success:
        - ./mvnw -B -Pcoverage clean verify coveralls:report
    - os: linux
      dist: trusty
      language: java
      jdk: openjdk11
    - os: linux
      dist: trusty
      language: java
      jdk: oraclejdk8
    - os: linux
      dist: trusty
      language: java
      jdk: oraclejdk11
    - os: windows
      language: bash
      before_script:
        - choco install adoptopenjdk11
        - export JAVA_HOME="$(dirname "$(dirname "$(find "/c/Program Files/AdoptOpenJDK" -name javac.exe)")")"
script:
  - ./mvnw -B -e verify
cache:
  directories:
    - $HOME/.m2
