language: java
matrix:
  include:
    - os: linux
      dist: trusty
      language: java
      jdk: openjdk8
    - os: linux
      dist: trusty
      language: java
      jdk: openjdk11
    - os: linux
      dist: trusty
      language: java
      jdk: oraclejdk8
    - os: linux
      dist: trusty
      language: java
      jdk: oraclejdk11
    - os: windows
      language: bash
      before_script:
       - choco install adoptopenjdk11
       - "export JAVA_HOME=$(dirname $(find '/Program Files/AdoptOpenJDK' -name 'javac'))"
script:
  - ./mvnw -B -e verify site site:stage
after_success:
  - ./mvnw -B -Pcoverage clean verify coveralls:report
cache:
  directories:
    - $HOME/.m2
