language: java
jdk:
  - openjdk8
  - openjdk11
  - oraclejdk8
  - oraclejdk11
os:
  - linux
  - windows
dist: trusty
script:
  - ./mvnw -B -e verify site site:stage
after_success:
  - ./mvnw -B -Pcoverage clean verify coveralls:report
cache:
  directories:
    - $HOME/.m2
