language: java
jdk:
  - openjdk8
  - openjdk11
  - oraclejdk8
  - oraclejdk11
dist: trusty
script:
  - mvn -B -e verify site site:stage
after_success:
  - mvn -B -Pcoverage clean verify coveralls:report
cache:
  directories:
    - $HOME/.m2
