language: java
matrix:
  include:
    - os: linux
      dist: trusty
      language: java
      jdk: openjdk8
    - os: linux
      dist: trusty
      language: java
      jdk: openjdk11
    - os: linux
      dist: trusty
      language: java
      jdk: oraclejdk8
    - os: linux
      dist: trusty
      language: java
      jdk: oraclejdk11
script:
  - ./mvnw -B -e verify site site:stage
after_success:
  - ./mvnw -B -Pcoverage clean verify coveralls:report
cache:
  directories:
    - $HOME/.m2
